pipeline {
    agent { label 'AGENT-1' }

    stages {
        stage('Checkout') {
            steps {
                // Checkout the code from the repository
                git 'https://github.com/Anjina-devops/roboshop-project-configuration.git'

                // List files for debugging
                sh '''
                    ls -l
                    cd ec2
                    ls -l
                '''
            }
        }

        stage('Terraform Init') {
            steps {
                echo 'Initializing Terraform...'
                dir('ec2') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                echo 'Planning Terraform changes...'
                dir('ec2') {
                    sh 'terraform plan'
                }
            }
        }

        stage('Terraform Apply Approval') {
            steps {
                script {
                    def applyApproval = input(
                        id: 'userInputApply',
                        message: 'Do you want to apply the Terraform plan?',
                        parameters: [
                            [$class: 'BooleanParameterDefinition', name: 'Approve', defaultValue: true]
                        ]
                    )

                    if (applyApproval == true) {
                        echo 'User approved Terraform apply.'
                        dir('ec2') {
                            sh 'terraform apply -auto-approve'
                        }
                    } else {
                        echo 'Terraform apply skipped by user.'
                    }
                }
            }
        }

        stage('Terraform Destroy Approval') {
            steps {
                script {
                    def destroyApproval = input(
                        id: 'userInputDestroy',
                        message: 'Do you want to destroy the infrastructure?',
                        parameters: [
                            [$class: 'BooleanParameterDefinition', name: 'Approve', defaultValue: false]
                        ]
                    )

                    if (destroyApproval == true) {
                        echo 'User approved Terraform destroy.'
                        dir('ec2') {
                            sh 'terraform destroy -auto-approve'
                        }
                    } else {
                        echo 'Terraform destroy skipped by user.'
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully.'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
